// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vNYHYdba5dDm6wfqFaSoQa
// Component: eLMfPBLHlWhr
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { ProductBox } from "@plasmicpkgs/commerce";
import { ProductTextField } from "@plasmicpkgs/commerce";
import { ProductPriceComponent } from "@plasmicpkgs/commerce";
import LinkButton from "../../LinkButton"; // plasmic-import: 6vEjUyLNvQQ4/component
import { ProductMedia } from "@plasmicpkgs/commerce";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_wo_ma.module.css"; // plasmic-import: vNYHYdba5dDm6wfqFaSoQa/projectcss
import sty from "./PlasmicFeatureItem.module.css"; // plasmic-import: eLMfPBLHlWhr/css

createPlasmicElementProxy;

export const PlasmicFeatureItem__VariantProps = new Array();

export const PlasmicFeatureItem__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFeatureItem__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <ProductBox
        data-plasmic-name={"productBox"}
        data-plasmic-override={overrides.productBox}
        className={classNames("__wab_instance", sty.productBox)}
        id={"unlimited-table-collection"}
      >
        <ph.DataCtxReader>
          {$ctx => (
            <React.Fragment>
              <div className={classNames(projectcss.all, sty.freeBox__kqPwT)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__gU8Zl)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__auK6)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vf8Un)}
                  >
                    <ProductTextField
                      className={classNames(
                        "__wab_instance",
                        sty.productTextField__mmtQx
                      )}
                      field={"name"}
                    />

                    <ProductTextField
                      className={classNames(
                        "__wab_instance",
                        sty.productTextField__qKth8
                      )}
                      field={"description"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__yh9X)}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text
                        )}
                      >
                        {"Starting from "}
                      </div>
                      <ProductPriceComponent
                        data-plasmic-name={"productPrice"}
                        data-plasmic-override={overrides.productPrice}
                        className={classNames(
                          "__wab_instance",
                          sty.productPrice
                        )}
                      />
                    </div>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__hspgf)}
                    >
                      <LinkButton
                        data-plasmic-name={"linkButton"}
                        data-plasmic-override={overrides.linkButton}
                        className={classNames("__wab_instance", sty.linkButton)}
                        text={"View More"}
                        type={"solidOrange"}
                      />
                    </p.Stack>
                  </p.Stack>
                </div>
              </div>
              <ProductMedia
                data-plasmic-name={"productMedia"}
                data-plasmic-override={overrides.productMedia}
                className={classNames("__wab_instance", sty.productMedia)}
              />
            </React.Fragment>
          )}
        </ph.DataCtxReader>
      </ProductBox>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "productBox",
    "text",
    "productPrice",
    "linkButton",
    "productMedia"
  ],

  productBox: [
    "productBox",
    "text",
    "productPrice",
    "linkButton",
    "productMedia"
  ],

  text: ["text"],
  productPrice: ["productPrice"],
  linkButton: ["linkButton"],
  productMedia: ["productMedia"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFeatureItem__ArgProps,
          internalVariantPropNames: PlasmicFeatureItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFeatureItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeatureItem";
  } else {
    func.displayName = `PlasmicFeatureItem.${nodeName}`;
  }
  return func;
}

export const PlasmicFeatureItem = Object.assign(
  // Top-level PlasmicFeatureItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productBox: makeNodeComponent("productBox"),
    text: makeNodeComponent("text"),
    productPrice: makeNodeComponent("productPrice"),
    linkButton: makeNodeComponent("linkButton"),
    productMedia: makeNodeComponent("productMedia"),
    // Metadata about props expected for PlasmicFeatureItem
    internalVariantProps: PlasmicFeatureItem__VariantProps,
    internalArgProps: PlasmicFeatureItem__ArgProps
  }
);

export default PlasmicFeatureItem;
/* prettier-ignore-end */
