// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vNYHYdba5dDm6wfqFaSoQa
// Component: 5s29WsEddxfu
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_wo_ma.module.css"; // plasmic-import: vNYHYdba5dDm6wfqFaSoQa/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: 5s29WsEddxfu/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: qRer315GXg-3/icon

createPlasmicElementProxy;

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRatings__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <StarIcon
          className={classNames(projectcss.all, sty.svg__dzNki, {
            [sty.svgstars_five__dzNkiiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_zero__dzNki34Ajm]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__vuynG, {
            [sty.svgstars_five__vuynGiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__vuynGt4U7X]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__vuynGXwQft]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__vuynGdCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__vuynGCgoTj]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__vuynG34Ajm]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__tBkJ, {
            [sty.svgstars_five__tBkJiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__tBkJt4U7X]: hasVariant($state, "stars", "four"),
            [sty.svgstars_one__tBkJXwQft]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__tBkJdCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__tBkJCgoTj]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__tBkJ34Ajm]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__gx9O, {
            [sty.svgstars_five__gx9OITI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__gx9OT4U7X]: hasVariant($state, "stars", "four"),
            [sty.svgstars_one__gx9OXwQft]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__gx9ODCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__gx9OCgoTj]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__gx9O34Ajm]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__j4Boo, {
            [sty.svgstars_five__j4BoOiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__j4Boot4U7X]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__j4BooXwQft]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__j4BoodCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__j4BooCgoTj]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__j4Boo34Ajm]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___3XJb0, {
            [sty.svgstars_five___3XJb0ITI9]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___3XJb0T4U7X]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one___3XJb0XwQft]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three___3XJb0DCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___3XJb0CgoTj]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero___3XJb034Ajm]: hasVariant(
              $state,
              "stars",
              "zero"
            )
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___2DtR4, {
            [sty.svgstars_five___2DtR4ITI9]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___2DtR4T4U7X]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_three___2DtR4DCljA]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___2DtR4CgoTj]: hasVariant($state, "stars", "two")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__iIfPq, {
            [sty.svgstars_five__iIfPQiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__iIfPqt4U7X]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_three__iIfPqdCljA]: hasVariant(
              $state,
              "stars",
              "three"
            )
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__tfMTw, {
            [sty.svgstars_five__tfMTwiTI9]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__tfMTwT4U7X]: hasVariant($state, "stars", "four")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___3RkGc, {
            [sty.svgstars_five___3RkGCiTI9]: hasVariant($state, "stars", "five")
          })}
          role={"img"}
        />
      </p.Stack>
      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
