// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vNYHYdba5dDm6wfqFaSoQa
import * as React from "react";
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-swell";

export default function GlobalContextsProvider(props) {
  const { children, commerceProviderComponentProps } = props;
  return (
    <CommerceProviderComponent
      {...commerceProviderComponentProps}
      publicKey={
        commerceProviderComponentProps &&
        "publicKey" in commerceProviderComponentProps
          ? commerceProviderComponentProps.publicKey
          : "pk_BukiQnhoM3Q35VxEyNCtmZHrZKSGNUBk"
      }
      storeId={
        commerceProviderComponentProps &&
        "storeId" in commerceProviderComponentProps
          ? commerceProviderComponentProps.storeId
          : "plasmic-commerce-furn"
      }
    >
      {children}
    </CommerceProviderComponent>
  );
}
